### ISSUE TITLE
Improve category entity

### ISSUE THREAD

**Issue by FieryCod** [knit-pk/api-v1-php#114]
We need following pieces of information in category entity:
- `metaDescription` and `metaTitle` for `seo` purposes
- `description` and `totalItems` of articles in the category for categories widget

The response from the API should be as follows:
``` 
[ 
     {
       '@id': '/categories/3e46358e-2d57-4564-be10-b2416344e356',
       '@type': 'Category',
       id: '3e46358e-2d57-4564-be10-b2416344e356',
       code: 'announcement',
       name: 'Announcement' ,
       metaDescription: 'some meta 1',
       metaTitle: 'some meta title 1',
       totalItems: 1,
       description: 'This is some extra description of the category 1'
     },
     { 
       '@id': '/categories/8d78fb09-942a-4162-9cc0-1e3b602ad6f4',
       '@type': 'Category',
       id: '8d78fb09-942a-4162-9cc0-1e3b602ad6f4',
       code: 'news',
       name: 'News' ,
       metaDescription: 'some meta 2',
       metaTitle: 'some meta title 2',
       totalItems: 10,
       description: 'This is some extra description of the category 2'
     },
     { 
       @id': '/categories/bad4891f-caf2-42e7-a19a-9ffabcb080c7',
       '@type': 'Category',
       id: 'bad4891f-caf2-42e7-a19a-9ffabcb080c7',
       code: 'article',
       name: 'Article',
       metaDescription: 'some meta 3',
       metaTitle: 'some meta title 3',
       totalItems: 2,
       description: 'This is some extra description of the category 3'
     } 
]
```

**Comment by k911** [comment]
Just one adjustment:

- `totalItems` field must be named as `articlesCount`, because `totalItems` is used in *-to-many relations, indicating total items in collection, and for consistency with other already used '*Count' columns.

And some questions:
What is difference between `metaDescription` and `description`? Could you please specify requirements for these fields: Are they required? Are they limited? Etc.?
Is it possible that 'metaFields' will be used in another Entity? Then I could create Embeddable "meta" object having "title" and "description".

**Comment by tosektosek** [comment]
Actually, I would add one requirement: 
120<meta description<300.
I've read more about it and having more than 120 words can (but not 100% guarantee) that our description will not end with one line in google search results.

Also I want to share with you with google sentence:
QUOTE: “Avoid keyword stuffing. Avoid repeated or boilerplate titles.” Google, 2018
That is the most important requirement. The rest of SEO stuff will be developed after release.

**Comment by k911** [comment]
@FieryCod @tosektosek 

Thanks for clarification! :)

**Comment by tosektosek** [comment]
@k911 Right, characters, thanks 👍
